---
- name: Enable nftables
  ansible.builtin.systemd:
   name: nftables
   state: started
   enabled: true

- name: Update nftable config
  ansible.builtin.template:
   src: nftables.conf.j2
   dest: /etc/nftables.conf
   owner: root
   group: root
   mode: "0775"
  notify:
   - Restart nftables service
